### ISSUE TITLE
TypeScript TypeDefinition is missing

### ISSUE THREAD

**Issue by sliwalker** [mark43/dexie-encrypted#1]
Thank you for developing this nice add-on.

Could you please provide TypeScript type definitions as soon as possible? 
Currently the package is not usable at all in our project. Tried to create a .d.ts but facing many issues on trying to get it to work.

**Comment by stutrek** [comment]
I'm glad you like it.

Can you provide more information? I'm confused about what type issues you may be seeing since this library doesn't change your database, it only adds hooks to it. You may need to bump the version of your database, since it does add a table that's used internally.

**Comment by sliwalker** [comment]
The issue are more of a TypeScript kind.

As the typings are missing I cannot really import your lib into my project without getting type errors. Eg. we do not allow the type "any".
Your package is defined as an ES6 module, so my attempts to write a d.ts failed. Tried to define a namespace, to declare a module and even just set a type for the encrypt function, but I cant get the types working.

Giving you one example what I did:
`declare namespace DexieEncrypted {
    interface cryptoOptions {
        [key: string]: string;
    }
}

declare class DexieEncrypted {
    /*
    _interopDefault(ex);
    overrideParseStoresSpec(origFunc);
    compareArrays(a, b);
    encryptObject(key:Uint8Array, object, nonce: Buffer);
    hideValue(input);
    */
    encrypt(
        db: Dexie.Database,
        key: Uint8Array,
        cryptoSettings: DexieEncrypted.cryptoOptions,
        nonceOverride: Buffer
    ): void;
}

export = DexieEncrypted;
export as namespace DexieEncrypted;`

This was one of many attempts to write typings for your project.
As I cant spend multiple hours to do that I just stopeed after some time and decided to ask you guys to privide proper typings for your project.

Does that help?

**Comment by stutrek** [comment]
One problem you may be having is that nonceOverride is not optional in your type, but it's not even documented because it's only meant for testing.

Until someone has time to do this, you might have to // @ts-ignore. If your rules don't allow that, you'll have to create the types yourself.

**Comment by schleiftier** [comment]
Hi, I am facing similar problems. For me the problem is that I cannot figure out how to write an ambient type declaration that is accepted by the typescript compiler.

I used to do that for AMD or CommonJS modules that exported a class, but so far I was unsuccessful to do so for `dex-encrypted` because it exports a function.

Having the type definitions included in the node module would really help alot.

**Comment by gurufordy** [comment]
Has this been abandoned?

**Comment by stutrek** [comment]
A PR that changes it to typescript would be accepted. However, it doesn't change the type of your database in any way, so it would only help with initial setup.

**Comment by stutrek** [comment]
Upgrade to version 2, it was rewritten in typescript!
