### ISSUE TITLE
TypeError: cannot read property 'toCollection' of undefined

### ISSUE THREAD

**Issue by dfahlander** [mark43/dexie-encrypted#2]
Hi! Thanks for this very interesting library. I've got the impression through issues over the years that this is really something that people need. And also really nice that it is designed to work with almost zero config.

However, when I was trying it out on both Dexie 2.x and 3.x I get the same error. I might be missing something. But the error I get is on line 160 where it expects a property db._encryptionSettings that is not defined. Tried to track it down but I couldn't find the place where it was supposed to be set.

**Comment by stutrek** [comment]
Hmmm... Do you need to bump your version for it to create that table?

**Comment by dfahlander** [comment]
When I search the code (index.js) for "_encryptionSettings", I only find it being read from and never set... Except on stores where it's set to '++id'.

**Comment by stutrek** [comment]
It's the very last line. It's entirely possible that I have a bug cause by a quirk in my testing environment.

**Comment by stutrek** [comment]
Tomorrow I'll do some testing. I'm also thinking of having make its own database rather than adding a table to yours, this issue is likely to hit many people.

**Comment by dfahlander** [comment]
I have the same version-bump requirement in dexie-observable but it does not seem to be a biggie for most people. And you make it very clear on the readme, so I don't think it will be a huge problem.

You might lose integrity if going over to use a separate db for the metadata. Also keep in mind people may delete one db but not the other in dev tools.

**Comment by stutrek** [comment]
I see it broken in your example. Error messages are also in need of improvement.

**Comment by dfahlander** [comment]
Found the issue. I was calling encrypt(db) AFTER having already defined the versions, including the bumped version number. I saw you have PR #3 that adds some checks. One problem with the PR is that db._encryptionSettings doesn't fail with NotFoundError but with TypeError: cannot read property 'toCollection' of undefined.

And if people happen to do like I did, they could be given a more concrete error message, that encrypt(db) has to be called before db.version() is called. This can be detected in encrypt() function - check that db.tables.length === 0 when encrypt() is called.

I will submit a PR with two suggested changes. Do what you want with it.

**Comment by stutrek** [comment]
Thank you! Is it just how I did it that requires that version is called after or is it something that can be worked around?

I'm having trouble with another error message. [Right here](https://github.com/mark43/dexie-encrypted/blob/d9de97d71e1b0cd8daaa10d050d8816dd2633b1b/index.js#L226) when I made a new error with a helpful message it got eaten somewhere in Dexie and I ended up with a generic Dexie error. Is there a way for me to get a good error message all the way back to the consumer?

**Comment by dfahlander** [comment]
It can be worked around. Instead of throwing (like I do in my pr) when db.tables.length > 0, just run db.version(db.verno).stores({}) to make the change into the last version. This is still before db.open happens so it's just about configuring db._dbschema and db._versions with your store.

Another pitfall would be people calling encrypt() after db.open, this would be more tricky case, but I suppose people would be fine with an error message in that case.

Regarding the exception eating thing..., I suppose the reason is that errors thrown in the implicit call to db.open() will be encapsulated with an OpenFailed error that has your exception in it's 'inner' property.

**Comment by dfahlander** [comment]
I updated my PR after som testing.

We have the following use cases:
1. User bumps version by adding a new empty version(2). The call to encrypt(db) is done BEFORE the versions are defined (correctly).
    - Everything should work as expected.

2. User forgets to bump version number.
    - With my PR, the user should get a OpenFailedError with an explaining message (even though encapsulated within an OpenFailedError - the message includes our error message (In my sample app the error message shows 'OpenFailedError: Error Dexie-encrypted can't find its encryption table. You may need to bump your database version'.

3. User calls encrypt after having defined the versions
    - My PR makes a call to db.version(db.verno).stores({}) to invoke the meta table, so it should still work as expected.

4. User calls encrypt after having called db.open().
    - My PR will make it throw new Error("Dexie-encrypt: The call to encrypt() cannot be done on an open database");


Still, I am having issues to get encrypting/decryption working after having reloaded my HTML page. It works perfectly when it opens up the first time. But second time it fails to load the encrypted values. I'll be filing this in another issue.

**Comment by stutrek** [comment]
Fixed in #4
