### ISSUE TITLE
Cannot use 'in' operator to search for 'then' in undefined

### ISSUE THREAD

**Issue by saurabhsep99** [mark43/dexie-encrypted#35]
When I use Custom Encryption Method It gives me that error  

https://codesandbox.io/s/dexie-encrypted-eh2qd?file=/db.js

**Comment by dfahlander** [comment]
Looking at it briefly I wonder why addToIndexedDb doesn't return a promise and why you don't await it? The code continues to getFromIndexedDb before finished writing.

**Comment by saurabhsep99** [comment]
I have now resolved the issue it is getting from my side package is working fine
