### ISSUE TITLE
Question: multiple users with separate keys

### ISSUE THREAD

**Issue by lifter035** [mark43/dexie-encrypted#6]
What would be the best strategy to have different records encrypted with different keys?
Is that possible? Or do I need to create separate db for each application user?

Thanks

**Comment by stutrek** [comment]
You'll have to create a separate db for each user, there's no way to use the key as a differentiator.

We just added a new feature that will let you erase the db or perform other actions if the key doesn't match, this may help your use case.

**Comment by lifter035** [comment]
@stutrek thanks already implemented multidb option and added removal of db onbeforeunload in case of IE Edge as indexeddb shim for compound indexes was not compatible with encryption and we had to support that browser until Chromium Edge is released, hopefully in January 2020
